server:
  port: 8080

spring:
  application:
    name: applyExecutorToService

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/applyExecutor
    username: root
    password: cheomuk201720^^

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher