name: draft-release
on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: /workflows/release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
