name: draft-release

on:
  pull_request:
    branches:
      - main
    types:
      - closed


permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: /workflows/release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
